
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mbti-rds.ctzpvwowlwov.ap-northeast-2.rds.amazonaws.com:3306/MBTI?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: mason
    password: masonmbti

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  logging.level:
    org.hibernate.SQL: debug

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


cloud:
  aws:
    s3:
      bucket: mbti-pic-bucket
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIARU7MLVIAZFVW5QBC
      secretKey: 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
